// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package selection

import (
	time "time"
)

type Event interface{}
type Like struct {
	Reaction  string
	Sent      time.Time
	Selection []string
	Collected []string
}
type Post struct {
	Message   string
	Sent      time.Time
	Selection []string
	Collected []string
}
