run:
  tests: true
  skip-dirs:
    - bin

linters-settings:
  errcheck:
    ignore: fmt:.*,[rR]ead|[wW]rite|[cC]lose,io:Copy
  revive:
    enable-all-rules: false
    rules:
      - name: empty-lines
  testifylint:
    disable-all: true
    enable:
      - expected-actual

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - typecheck
    - unconvert
    - unused

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
