version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - dupword
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Writer).Write
        - io.Copy
        - io.WriteString
    gocritic:
      enabled-checks:
        - emptyStringTest
        - equalFold
        - httpNoBody
        - nilValReturn
        - paramTypeCombine
        - preferFprint
        - yodaStyleExpr
    govet:
      disable:
        - fieldalignment
        - shadow
        - unusedwrite
      enable-all: true
    perfsprint:
      int-conversion: false
      err-error: false
      errorf: true
      sprintf1: false
      strconcat: false
    revive:
      enable-all-rules: false
      rules:
        - name: empty-lines
#        - name: use-any # this causes problems in some generated files
        - name: struct-tag
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-naming
        - name: exported
          disabled: true
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: superfluous-else
        - name: unused-parameter
          disabled: true
        - name: unreachable-code
        - name: redefines-builtin-id
    testifylint:
      disable-all: true
      enable:
        - blank-import
        - bool-compare
        - compares
        - empty
        - encoded-compare
        - error-is-as
        - error-nil
        - expected-actual
        - float-compare
        - go-require
        - len
        - negative-positive
        - nil-compare
        - require-error
        - useless-assert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
        path: _test\.go
      - linters:
          - gocritic
        path: codegen/testserver/.*/resolver\.go
      - linters:
          - gocritic
        path: _examples/federation/products/graph/entity.resolvers.go
      - path: graphql/map.go
        text: 'use-any: since GO 1.18 ''interface{}'' can be replaced by ''any'''
      - path: codegen/testserver/followschema/resolver.go
        text: 'use-any: since GO 1.18 ''interface{}'' can be replaced by ''any'''
      - path: codegen/testserver/singlefile/resolver.go
        text: 'use-any: since GO 1.18 ''interface{}'' can be replaced by ''any'''
      - linters:
          - staticcheck
        path: codegen/testserver/generated_test.go
        text: SA1019
      - linters:
          - staticcheck
        path: plugin/modelgen/models_test.go
        text: SA1019
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - third_party$
      - builtin$
      - examples$
