run:
  tests: true
  timeout: 5m

linters-settings:
  gocritic:
    enabled-checks:
      - emptyStringTest
      - equalFold
      - httpNoBody
      - nilValReturn
      - paramTypeCombine
      - preferFprint
      - yodaStyleExpr
  errcheck:
    exclude-functions:
      - (io.Writer).Write
      - io.Copy
      - io.WriteString
  perfsprint:
    int-conversion: false
    err-error: false
    errorf: true
    sprintf1: false
    strconcat: false
  revive:
    enable-all-rules: false
    rules:
      - name: empty-lines
      - name: use-any
  testifylint:
    disable-all: true
    enable:
      - blank-import
      - bool-compare
      - compares
      - empty
      - error-is-as
      - error-nil
      - expected-actual
      - float-compare
      - go-require
      - len
      - negative-positive
      - nil-compare
      - require-error
      - useless-assert

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - typecheck
    - unconvert
    - unused

issues:
  exclude-dirs:
    - bin
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - errcheck
    # It's autogenerated code.
    - path: codegen/testserver/.*/resolver\.go
      linters:
        - gocritic
    # Disable revive.use-any for backwards compatibility
    - path: graphql/map.go
      text: "use-any: since GO 1.18 'interface{}' can be replaced by 'any'"
    - path: codegen/testserver/followschema/resolver.go
      text: "use-any: since GO 1.18 'interface{}' can be replaced by 'any'"
    - path: codegen/testserver/singlefile/resolver.go
      text: "use-any: since GO 1.18 'interface{}' can be replaced by 'any'"
