language: go
sudo: required

go:
  - "1.x"
  - "1.9"

go_import_path: github.com/vektah/gqlgen

install:
    - >
          sudo curl -L -o /bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 &&
          sudo chmod +x /bin/dep &&
          go get -u github.com/alecthomas/gometalinter github.com/vektah/gorunpkg &&
          gometalinter --install &&
          dep ensure -vendor-only
    - go install -v . && go get -u github.com/vektah/dataloaden

script:
    - go generate ./... && if [[ $(git --no-pager diff) ]] ; then echo "you need to run go generate" ; git --no-pager diff ; exit 1 ; fi
    - go test -race ./...
    - gometalinter --vendor ./...
