package mixedrequires

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94-dev

import (
	"context"

	"github.com/99designs/gqlgen/plugin/federation/testdata/mixedrequires/generated"
	"github.com/99designs/gqlgen/plugin/federation/testdata/mixedrequires/generated/model"
)

// FindPlanetByName is the resolver for the findPlanetByName field. Planet uses
// the computed @requires strategy, so `size` is resolved separately (see
// schema.resolvers.go) — this resolver only fills the key.
func (r *entityResolver) FindPlanetByName(ctx context.Context, name string) (*model.Planet, error) {
	return &model.Planet{Name: name}, nil
}

// FindManyProductByIDs is the resolver for the findManyProductByIDs field.
// Product uses the preloaded strategy, so each rep arrives with its
// @requires field (Category) populated and `display` is computed here.
func (r *entityResolver) FindManyProductByIDs(ctx context.Context, reps []*model.ProductByIDsInput) ([]*model.Product, error) {
	products := make([]*model.Product, len(reps))
	for i, rep := range reps {
		products[i] = &model.Product{
			ID:      rep.ID,
			Display: "display for " + rep.Category,
		}
	}
	return products, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
