models:
  Droid:
    model: github.com/vektah/gqlgen/example/starwars.Droid
  FriendsConnection:
    model: github.com/vektah/gqlgen/example/starwars.FriendsConnection
  FriendsEdge:
    model: github.com/vektah/gqlgen/example/starwars.FriendsEdge
  Human:
    model: github.com/vektah/gqlgen/example/starwars.Human
  Review:
    model: github.com/vektah/gqlgen/example/starwars.Review
  ReviewInput:
    model: github.com/vektah/gqlgen/example/starwars.Review
  Starship:
    model: github.com/vektah/gqlgen/example/starwars.Starship
