models:
  Droid:
    model: github.com/monzo/gqlgen/example/starwars.Droid
  FriendsConnection:
    model: github.com/monzo/gqlgen/example/starwars.FriendsConnection
  Human:
    model: github.com/monzo/gqlgen/example/starwars.Human
  Review:
    model: github.com/monzo/gqlgen/example/starwars.Review
  ReviewInput:
    model: github.com/monzo/gqlgen/example/starwars.Review
  Starship:
    fields:
      length:
        resolver: true
