// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package out_embedded_structs_models

type Element interface {
	IsNode()
	IsElement()
	GetID() string
	GetName() string
}

type Node interface {
	IsNode()
	GetID() string
}

type BaseElement struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (BaseElement) IsNode()            {}
func (this BaseElement) GetID() string { return this.ID }

type BaseNode struct {
	ID string `json:"id"`
}

type Carbon struct {
	Footprint string `json:"footprint"`
	BaseElement
}

func (Carbon) IsElement()           {}
func (this Carbon) GetID() string   { return this.ID }
func (this Carbon) GetName() string { return this.Name }

func (Carbon) IsNode() {}

type Magnesium struct {
	Types int `json:"types"`
	BaseElement
}

func (Magnesium) IsElement()           {}
func (this Magnesium) GetID() string   { return this.ID }
func (this Magnesium) GetName() string { return this.Name }

func (Magnesium) IsNode() {}

type Potassium struct {
	Price float64 `json:"price"`
	BaseElement
}

func (Potassium) IsElement()           {}
func (this Potassium) GetID() string   { return this.ID }
func (this Potassium) GetName() string { return this.Name }

func (Potassium) IsNode() {}

type Query struct {
}
