// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package protogetters

import (
	"context"

	"github.com/99designs/gqlgen/codegen/testserver/protogetters/models"
)

type Stub struct {
	QueryResolver struct {
		User func(ctx context.Context, id string) (*models.User, error)
	}
}

func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}

type stubQuery struct{ *Stub }

func (r *stubQuery) User(ctx context.Context, id string) (*models.User, error) {
	return r.QueryResolver.User(ctx, id)
}
