package batchresolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86-dev

import (
	"context"
	"fmt"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// NullableBatchBatch is the batch resolver for the nullableBatch field.
func (r *userResolver) NullableBatchBatch(ctx context.Context, objs []*User) ([]*Profile, []error) {
	panic("not implemented: NullableBatchBatch - nullableBatch")
}

// NullableNonBatch is the resolver for the nullableNonBatch field.
func (r *userResolver) NullableNonBatch(ctx context.Context, obj *User) (*Profile, error) {
	panic("not implemented")
}

// NonNullableBatchBatch is the batch resolver for the nonNullableBatch field.
func (r *userResolver) NonNullableBatchBatch(ctx context.Context, objs []*User) ([]*Profile, []error) {
	panic("not implemented: NonNullableBatchBatch - nonNullableBatch")
}

// NonNullableNonBatch is the resolver for the nonNullableNonBatch field.
func (r *userResolver) NonNullableNonBatch(ctx context.Context, obj *User) (*Profile, error) {
	panic("not implemented")
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
