package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45-dev

import (
	"context"

	"github.com/99designs/gqlgen/_examples/enum/model"
)

// Int is the resolver for the int field.
func (r *queryResolver) Int(ctx context.Context, typedN *model.IntTyped, untypedN *int, typed model.IntTyped, untyped int) ([]model.IntTyped, error) {
	return []model.IntTyped{model.IntTypedOne, model.IntTypedTwo}, nil
}

// String is the resolver for the string field.
func (r *queryResolver) String(ctx context.Context, typedN *model.StringTyped, untypedN *string, typed model.StringTyped, untyped string) ([]model.StringTyped, error) {
	return []model.StringTyped{model.StringTypedOne, model.StringTypedTwo}, nil
}

// Bool is the resolver for the bool field.
func (r *queryResolver) Bool(ctx context.Context, typedN *model.BoolTyped, untypedN *bool, typed model.BoolTyped, untyped bool) ([]model.BoolTyped, error) {
	return []model.BoolTyped{model.BoolTypedTrue, model.BoolTypedFalse}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
