// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package splitpackages

// split_runtime.generated.go is intentionally thin for split-packages.
// Execution dispatch now lives in the generated root gateway and shard packages.
