// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package structvalslices

type Page struct {
	ID   string `json:"id"`
	Str  string `json:"str"`
	Tags []Tag  `json:"tags"`
}

type Tag struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

type TagInput struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}
