extends: default
rules:
  braces: disable
  brackets: disable
  colons: enable
  commas: disable
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: disable
  empty-values: disable
  hyphens: enable
  indentation:
    spaces: 2
    check-multi-line-strings: false
    indent-sequences: false
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: disable
  truthy:
    allowed-values: ['true', 'false', 'on'] # 'on' for GH action trigger
    check-keys: false
