// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package omittypedinputunmarshalers

import (
	"context"
)

type Stub struct {
	QueryResolver struct {
		Search func(ctx context.Context, filters SearchFilters) (string, error)
	}
}

func (r *Stub) Query() QueryResolver {
	return &stubQuery{r}
}

type stubQuery struct{ *Stub }

func (r *stubQuery) Search(ctx context.Context, filters SearchFilters) (string, error) {
	return r.QueryResolver.Search(ctx, filters)
}
