// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package zerovaluenonnullobjectfields

type Child struct {
	Name string `json:"name"`
}

type Parent struct {
	ID    string `json:"id"`
	Child *Child `json:"child"`
}

type Query struct {
}
