// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Thing interface {
	IsThing()
	GetID() string
}

type EmailHost struct {
	ID string `json:"id"`
}

func (EmailHost) IsEntity() {}

func (EmailHost) IsThing()           {}
func (this EmailHost) GetID() string { return this.ID }

type Manufacturer struct {
	ID string `json:"id"`
}

func (Manufacturer) IsEntity() {}

type ProductByManufacturerIDAndIDsInput struct {
	ManufacturerID string `json:"ManufacturerID"`
	ID             string `json:"ID"`
}

type Query struct {
}
