#!/bin/bash

# Script to check the coverage by running tests and merging profiles
set -o errexit
set -o nounset
set -o xtrace
set -o pipefail

# set -euxo pipefail is short for:
# set -e, -o errexit: stop the script when an error occurs
# set -u, -o nounset: detects uninitialised variables in your script and exits with an error (including Env variables)
# set -x, -o xtrace: prints every expression before executing it
# set -o pipefail: If any command in a pipeline fails, use that return code for whole pipeline instead of final success


#set -euo pipefail

function is_bin_in_path {
  builtin type -P "$1" &> /dev/null
}

export SED_COMMAND="gsed"
! is_bin_in_path gsed && export SED_COMMAND="sed"

join () {
  local IFS="$1"
  shift
  echo "$*"
}

echo "Installing goveralls latest"
go install github.com/mattn/goveralls@latest
echo "Collecting Test Package List"
# ${SED_COMMAND} 's/^\|$/"/g'|
pkgs="$(go list github.com/99designs/gqlgen/... 2> /dev/null | grep -v "integration" | grep -v "_examples" |grep -v "plugin/resolvergen/testdata" | grep -v "plugin/federation/testdata" | grep -v "plugin/resolvergen/testdata" | grep -v "invalid-packagename" | grep -v "generated-default")"

deps=$(echo "${pkgs}" | tr ' ' ",")
# -covermode atomic
echo "mode: atomic" > /tmp/coverage.out.tmp
echo "Attempting to create initial coverage profile"
for pkg in $pkgs; do
    go test -v -race -cover -coverpkg "$deps" -coverprofile=/tmp/profile.tmp "${pkg}"

    if [ -f /tmp/profile.tmp ]; then
        tail -n +2 /tmp/profile.tmp >> /tmp/coverage.out.tmp
        rm /tmp/profile.tmp
    fi
done;

# this was the old way and it did not work very well:
# go test -covermode atomic -coverprofile=/tmp/coverage.out.tmp -coverpkg=./...

# ignore protobuf files
grep -v ".pb.go" < /tmp/coverage.out.tmp > /tmp/coverage.out

ignore_list=(
  '_examples/*/*'
  '_examples/*/*/*'
  'integration/*'
  'integration/*/*'
  'codegen/testserver/**/*generated*'
  'codegen/testserver/**/*generated*/**'
  'codegen/testserver/**/models-gen.go'
  'codegen/testserver/**/resolver.go'
  'plugin/resolvergen/testdata/*/*'
  'plugin/modelgen/*/*'
  'plugin/federation/testdata/*/*/*'
  '*/generated.go'
  '*/*/generated.go'
  '*/*/*/generated.go'
  'graphql/executable_schema_mock.go'
)
ignore=$(join , "${ignore_list[@]}")

goveralls -coverprofile=/tmp/coverage.out -service=github "-ignore=$ignore"
