#!/bin/bash

set -euo pipefail

cd integration

date
go run ./server/server.go &

sleep 5
curl -s --connect-timeout 5 \
    --max-time 10 \
    --retry 5 \
    --retry-delay 5 \
    --retry-max-time 40 \
    --retry-connrefused \
    localhost:8080 > /dev/null

echo "### running jest integration spec"
./node_modules/.bin/jest --color


echo "### validating introspected schema"
./node_modules/.bin/graphql-codegen

if ! diff <(tail -n +3 schema-expected.graphql) <(tail -n +3 schema-fetched.graphql) ; then
    echo "The expected schema has changed, you need to update schema-expected.graphql with any expected changes"
    exit 1
fi
