name: Continuous Integration
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.13
    steps:
      - uses: actions/checkout@v1
      - run: go mod download
      - run: .github/workflows/check-fmt
      - run: .github/workflows/check-linting
      - run: .github/workflows/check-generate

  test:
    runs-on: ubuntu-latest
    container: golang:1.13
    steps:
      - uses: actions/checkout@v1
      - run: go mod download
      - run: go test -race ./...

  coverage:
    runs-on: ubuntu-latest
    container: golang:1.13
    steps:
      - uses: actions/checkout@v1
      - run: go mod download
      - run: .github/workflows/check-coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  integration:
    runs-on: ubuntu-latest
    container: alpine:3.10
    steps:
      - uses: actions/checkout@v1
      - run: apk add --no-cache --no-progress nodejs npm go musl-dev git bash
      - run: go mod download
      - run: cd integration ; npm install
      - run: .github/workflows/check-integration

  federation:
    runs-on: ubuntu-latest
    container: alpine:3.10
    steps:
      - uses: actions/checkout@v1
      - run: apk add --no-cache --no-progress nodejs npm go musl-dev git bash
      - run: go mod download
      - run: cd example/federation ; npm install
      - run: .github/workflows/check-federation

  windows:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1
      - run: go generate ./...
      - run: go test -timeout 20m ./...
