name: goreleaser

on:
  push:
    branches:
      - entropy
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.FOSS_PACKAGE_TOKEN }}
          WITH_V: true
      - name: Bump version and push tag (no v)
        uses: anothrNick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.FOSS_PACKAGE_TOKEN }}
          WITH_V: false
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: login
        run: echo $FOSS_PACKAGE_TOKEN  | docker login -u $FOSS_PACKAGE_USER --password-stdin ghcr.io
        env:
          FOSS_PACKAGE_TOKEN: ${{ secrets.FOSS_PACKAGE_TOKEN }}
          FOSS_PACKAGE_USER: ${{ secrets.FOSS_PACKAGE_USER }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.143.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.FOSS_PACKAGE_TOKEN }}
      -
        name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel: activity
          status: SUCCESS
          color: good

      -
        name: Notify slack fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v2
        with:
          channel: activity
          status: FAILED
          color: danger
