name: Integration
on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize]
env:
  GOTOOLCHAIN: local
# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        go: ["1.26", "1.25"]
        node: [22]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      with:
        persist-credentials: "false"
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v5
      with:
        node-version: ${{ matrix.node }}
    - run: go mod download
    - run: cd integration ; npm ci
    - run: .github/workflows/check-integration
  federation:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        go: ["1.26", "1.25"]
        node: [22]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      with:
        persist-credentials: "false"
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v5
      with:
        node-version: ${{ matrix.node }}
    - run: go mod download
    - run: cd _examples/federation ; npm install
    - run: .github/workflows/check-federation
  init:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        go: ["1.26", "1.25"]
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      with:
        persist-credentials: "false"
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: ${{ matrix.go }}
    - run: .github/workflows/check-init
