name: test report
on:
  workflow_run:
    workflows: ["Test"]
    types:
    - completed
permissions:
  checks: write
jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Download Test Report
      uses: dawidd6/action-download-artifact@8305c0f1062bb0d184d09ef4493ecb9288447732 # v20
      with:
        name: junit-test-results
        workflow: ${{ github.event.workflow.id }}
        run_id: ${{ github.event.workflow_run.id }}
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386 # v5
      with:
        commit: ${{github.event.workflow_run.head_sha}}
        report_paths: '**/*.xml'
